apiVersion: v1
kind: ReplicationController
metadata:
  name: contrail-frontend
spec:
  replicas: 3
  selector:
    app: contrail-frontend
  template:
    metadata:
      name: contrail-frontend
      labels:
        app: contrail-frontend
    spec:
      containers:
      - name: contrail-frontend
        image: savvythru/contrail-frontend-app
        ports:
        - containerPort: 80
